# Generated by Django 5.0 on 2024-11-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admRrhh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='imagen_asig',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesAsig/', verbose_name='Imagen'),
        ),
    ]
