# Generated by Django 5.0 on 2025-02-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admRrhh', '0002_asignacion_imagen_asig'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='monto_env',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
